### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by cjlortie** [MarioZuliani/Chapter-2#2]
Dataframe 1.  
site, plot, shrub density, measure, total number of animals, total number of species of animals.  

Dataframe 2.  
site, plots, shrub density, measure, animal species, total number of animals.

**Comment by cjlortie** [comment]
measure is the method
so put all three datasets together
compile it to just daily totals
also have two vectors for the plot
shrub_density (actual number of shrubs in plot from 0 to...) and shrub_density_category (put zero, low, medium, high) SO we are DOUBLE coding the plot type.

site as Elkhorn a, Elkhorn b
plot is just 1,2,3 or 4 right

**Comment by cjlortie** [comment]
also, where is you microclimate data for each plot (ie for each 10m plot)?
we need those data too please.

**Comment by MarioZuliani** [comment]
For Microclimate data, I believe Nargol has that data for the shrubs we did in the sites.

**Comment by cjlortie** [comment]
for the column 'shrub_density' put an actual number from 0 to howvever many shrubs you counted in each 10m plot.  

ALSO - did you use data from Jenna at all - ie the measure of total shrub cover in each 10m plot?

**Comment by MarioZuliani** [comment]
> for the column 'shrub_density' put an actual number from 0 to howvever many shrubs you counted in each 10m plot.
> 
> ALSO - did you use data from Jenna at all - ie the measure of total shrub cover in each 10m plot?

**Comment by MarioZuliani** [comment]
I dont know what i just closed or how, but in regards to the previous question. I didn't end up using Jenna's cover stuff. It was for a different area and the species there weren't Ephedra

**Comment by cjlortie** [comment]
jennas data - just put in methods that you used remote imagery to select sites in addition to field surveys.

**Comment by cjlortie** [comment]
1-2
Two compiled to day animal datasets. 
We can then pivot_wider the second one with species as a rows to Columns for
You to run your vegan code again if you need. 

3
Site data. Shrub siZes counts density whatever you have. We will the left_join select columns to the
Complied files

4
Microclimate. Maybe Nargol has clean code but wrangle to day then hourly Just like hers. Then we can join the unique overlap days to your compiled and have one temp or climate column too. Plus we also just want to do a separate test of zero
Shrub sites are hotter than high density sites etc. 

5
Whatever data Jenna have you for your 8 sites.
